export const AUTH_STATE_LOADING = 'AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED = 'AUTH_STATE_FAILED';
export const AUTH_STATE_LOGOUT = 'AUTH_STATE_LOGOUT';
export const AUTH_STATE_UPDATE = 'AUTH_STATE_UPDATE';