export const AUTH_STATE_LOADING = 'AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED = 'AUTH_STATE_FAILED';
export const AUTH_STATE_LOGOUT = 'AUTH_STATE_LOGOUT';
export const AUTH_STATE_UPDATE = 'AUTH_STATE_UPDATE';
export const AUTH_STATE_UPDATE_ROLE = 'AUTH_STATE_UPDATE_ROLE';

export const CONTRACT_MAIN_UPDATE = "CONTRACT_MAIN_UPDATE";
export const CONTRACT_FARMER_UPDATE = "CONTRACT_FARMER_UPDATE";
export const CONTRACT_MANUFACTURER_UPDATE = "CONTRACT_MAIN_UPDATE";
export const CONTRACT_STAKEHOLDER_UPDATE = "CONTRACT_STAKEHOLDER_UPDATE";
export const CONTRACT_PRODUCT_UPDATE = "CONTRACT_PRODUCT_UPDATE";