export const AUTH_STATE_LOADING = 'AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED = 'AUTH_STATE_FAILED';
export const AUTH_STATE_ENABLE_WEB3 = 'AUTH_STATE_ENABLE_WEB3';
export const AUTH_STATE_DISABLE_WEB3 = 'AUTH_STATE_DISABLE_WEB3';
export const AUTH_STATE_LOGIN = 'AUTH_STATE_LOGIN';
export const AUTH_STATE_LOGOUT = 'AUTH_STATE_LOGOUT';
export const AUTH_STATE_STAKEHOLDER = 'AUTH_STATE_STAKEHOLDER';

export const CONTRACT_STATE_LOADING = 'CONTRACT_STATE_LOADING';
export const CONTRACT_STATE_FAILED = 'CONTRACT_STATE_FAILED';
export const CONTRACT_STATE_MAIN = 'CONTRACT_STATE_MAIN';
export const CONTRACT_STATE_FARMER = 'CONTRACT_STATE_FARMER';
export const CONTRACT_STATE_MANUFACTURER = 'CONTRACT_STATE_MANUFACTURER';
export const CONTRACT_STATE_STAKEHOLDER = 'CONTRACT_STATE_STAKEHOLDER';
export const CONTRACT_STATE_PRODUCT = 'CONTRACT_STATE_PRODUCT';
export const CONTRACT_STATE_STATS = 'CONTRACT_STATE_STATS';